# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Project build

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github 
        settings-path: ${{ github.workspace }} 
     
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        # output_file: $GITHUB_WORKSPACE/settings.xml
        servers: '[{ "id": "github", "username": "joshjohanning", "password": "${{ secrets.GHEC_TOKEN }}" }]'
        repositories: >
          [
            { 
              "id": "central",
              "url": "https://repo1.maven.org/maven2"
            },
            {
              "id": "github",
              "url": "https://maven.pkg.github.com/joshjohanning-org/github-maven-package-sample"
            }
          ]


    - run: cat $GITHUB_WORKSPACE/settings.xml
    
    - run: cat ~/.m2/settings.xml
    
    - name: Build with Maven
      run: mvn clean package -s ~/.m2/settings.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s ~/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GHEC_TOKEN }}
